Fix issue #1888: 补全OA回调信息
Wechat-Group/WxJava pull request #1891
Opened 2020-11-26 00:54 UTC by Gyv12345

2020-11-26 01:19 UTC, binarywang requested changes
注意修复单词错误

2020-11-26 01:19 UTC, binarywang commented on weixin-java-cp/src/main/java/me/chanjar/weixin/cp/bean/message/WxCpXmlMessage.java
> +    private List<Notifyer> notorieties;
这个单词是啥鬼？

2020-11-26 01:19 UTC, binarywang commented on weixin-java-cp/src/main/java/me/chanjar/weixin/cp/bean/message/WxCpXmlMessage.java
> +    public static class Comments implements Serializable{
这个应该用单数吧

2020-11-26 01:21 UTC, binarywang requested changes

2020-11-26 01:21 UTC, binarywang commented on weixin-java-cp/src/main/java/me/chanjar/weixin/cp/bean/message/WxCpXmlMessage.java
> +    public static class Details implements Serializable{
请使用单数

2020-11-26 01:40 UTC, Gyv12345 commented on weixin-java-cp/src/main/java/me/chanjar/weixin/cp/bean/message/WxCpXmlMessage.java
> +    public static class Details implements Serializable{
OK

2020-11-26 01:45 UTC, binarywang commented
你不用关闭，直接在你分支上提交commit即可，PR会自动更新

2020-11-27 01:50 UTC, binarywang approved these changes

2020-11-27 01:52 UTC, merged